# Generated by Django 5.0.6 on 2025-03-09 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kercui', '0002_patient_rendezvous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='patient',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('confirme', 'Confirmé'), ('en_attente', 'En attente'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
