# Generated by Django 5.0.6 on 2025-03-10 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kercui', '0003_remove_rendezvous_patient_rendezvous_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='user',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_patient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('CONFIRMÉ', 'Confirmé'), ('EN_ATTENTE', 'En attente'), ('ANNULÉ', 'Annulé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='type',
            field=models.CharField(choices=[('Consultation vidéo', 'Consultation vidéo'), ('Suivi médical', 'Suivi médical'), ('Première consultation', 'Première consultation'), ('Consultation en cabinet', 'Consultation en cabinet')], max_length=100),
        ),
    ]
